package.json
This project uses Object.groupBy, which requires Node 21+
This PR adds this requirement to `package.json` which will produce a warning on `npm install`
=> add engines to package.json for groupBy support

README.md, docker-compose.local.yaml, local/Dockerfile
#29
The execution method of the project was changed from `npm run dev` to Docker. New Docker configuration files were added, and the README.md file was updated to reflect these changes. This enables a more uniform development environment and makes the project easier to run.
=> Update project execution method to Docker

src/components/Header.js
=> feat: current nav button highlighted

src/utils/checks/description.js
Added mentioned fix to description file.
Closes #46 
- Added length check for the `repo.homepage` property before the `includes` check.
- This makes sure the check only moved to the `includes` check when the `homepage` is filled.
=> feat: Added additional property check for homepage in description

src/app/account/repo/checks/[id]/action.js, src/app/account/repo/checks/[id]/page.js, src/app/repo/list/page.js, src/app/repo/report/[id]/page.js, src/utils/checks/branches.js, src/utils/checks/goodFirstIssue.js
=> feat: public list

README.md
Closes #61 
Added the basic modifications to the setup required to use the codespaces cloud dev en provided by github.  Also added a space in a previous step to separate a/b
- [ X] My code follows the code style of this project.
- [ X] My change requires changes to the documentation.
- [X ] I have updated the documentation accordingly.
- [ N/A] All new and existing tests passed.
- [X ] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.
=> Update README.md with codespaces instructions

.github/workflows/docker.yml
=> feat: publish docker image

.env.example, package-lock.json, src/app/account/repo/add/action.js, src/app/account/repo/add/form.js, src/app/account/repo/add/page.js, src/app/account/repo/list/page.js, src/components/Alert.js, src/components/forms/Input.js
=> feat: limit amount of repos #72

package.json, prisma/migrations/20240806121744_community/migration.sql, prisma/schema.prisma, src/app/account/repo/checks/[id]/action.js, src/utils/checks/codeOfConduct.js, src/utils/checks/contributing.js, src/utils/checks/index.js, src/utils/checks/issueTemplates.js, src/utils/checks/license.js, src/utils/checks/pullRequestTemplate.js, src/utils/checks/readme.js, src/utils/github/getCommunityMetrics.js, src/utils/github/index.js
=> Feat community checks

prisma/migrations/20240807055406_labels/migration.sql, prisma/schema.prisma, src/utils/checks/index.js, src/utils/checks/labels.js, src/utils/github/getLabelsApi.js, src/utils/github/index.js
=> feat: labels check

package-lock.json, package.json, playwright.config.ts, src/config/flagsmith.js, src/instrumentation.js
=> Fix test defaults

.github/workflows/docker.yml
Instead of using artifact, use official secrets option in `docker/build-push-action` GHA
=> fix: use secret methods in docker/build-push-action GH Actions

src/app/account/repo/add/form.js, src/app/account/repo/add/page.js, src/app/account/repo/checks/[id]/page.js, src/app/account/repo/list/page.js, src/app/layout.js, src/app/repo/report/[id]/page.js, src/components/Alert.js, src/components/forms/SubmitButton.js, tests/data/github/referrers.json, tests/data/github/views.json, tests/setup/mocks/handlers.js
=> Refactored project components

src/components/Footer.js
=> fix: add margin-top to footer #159

compose.yaml
Fixes Issue: -  Change in docker compose.yaml 
Closes  #167
Added a volume over the 
Local files to container files i.e. .:/usr/src/app
And another for node modules so that they don't overlap i.e. /usr/src/app/node_modules
=> Synced local files to container files

src/app/api/auth/[...nextauth]/route.js
fixes #213 
Removed write access to public repos as not required
```diff
- scope: "read:user user:email public_repo read:project",
+ scope: "read:user user:email read:project",
```
After being deployed, I will force everyone to logout via the GitHub OAuth app, so new tokens with less permissions are recreated when people log in again
=> fix: removed write access as not required

src/app/account/repo/checks/[id]/form.js, src/components/forms/Input.js
closes #173 
Fixed PR https://github.com/EddieHubCommunity/HealthCheck/pull/175
=> feat: copy badge feature (#175)

next.config.mjs, src/app/account/repo/checks/[id]/form.js, src/app/account/repo/checks/[id]/page.js, src/app/api/report/latest/[id]/route.js
=> feat: badge click to latest report

.env.example, .github/workflows/checks.yml, src/app/api/system/checks/route.js
=> feat: run checks regularly on a schedule

src/components/Button.js, src/components/Heading.js
Closes #200 
Changed Link to target="_blank" in heading actions.
=> fix:target updated from self to blank

src/utils/checks/license.js
Fix typo and make no license message make more grammatical sense.
=> Update no licence text
